services:
  postgres:
    image: postgres:16
    container_name: finanzas_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - finanzas_postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: finanzas_api
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: local

      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}

      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION_MS: ${JWT_EXPIRATION_MS}

    ports:
      - "8080:8080"

volumes:
  finanzas_postgres_data: